apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nublado.fullname" . }}-wf-api
  labels:
    name: {{ template "nublado.fullname" . }}-wf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "nublado.fullname" . }}-wf-api
  template:
    metadata:
      labels:
        name: {{ template "nublado.fullname" . }}-wf-api
    spec:
      serviceAccountName: {{ template "nublado.fullname" . }}-hub
      securityContext:
        runAsUser: {{ .Values.hub.uid }}
        runAsGroup: {{ .Values.hub.gid }}
        fsGroup: {{ .Values.hub.gid }}
      containers:
        - name: {{ template "nublado.fullname" . }}-wf-api
          imagePullPolicy: "Always"
          image: {{ .Values.wf.image }}
          resources:
            limits:
              memory: 1G
              cpu: 1.0
            requests:
              memory: 512M
              cpu: 0.4
          ports:
            - containerPort: 8080
              name: api
          env:
            - name: HELM_TAG
              value: '{{ template "nublado.fullname" . }}'
            # Set to non-empty value to enable debugging.
            - name: DEBUG
              value: '{{.Values.debug}}'
            # Set to non-empty values to disable audience/signature
            #  verification
            - name: WF_NO_VERIFY_SIGNATURE
              value: '{{.Values.wf.no_verify_signature}}'
            - name: WF_NO_VERIFY_AUDIENCE
              value: '{{.Values.wf.no_verify_audience}}'
            # IP address to bind to
            - name: WF_API_ADDR
              value: '{{.Values.wf.api_addr}}'
          # If you use sqlite, you want this to persist sessions across
          #  jupyterhub restarts.
          volumeMounts:
            - name: metadata
              mountPath: /etc/metadata
              readOnly: false
            - name: fs-mounts
              mountPath: /opt/lsst/software/jupyterhub/mounts
            - name: resourcemap
              mountPath: /opt/lsst/software/jupyterhub/resources
            - name: jwt-cert
              mountPath: /opt/jwt
              readOnly: true
      volumes:
        - name: metadata
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
        - name: jwt-cert
          configMap:
            defaultMode: 420
            items:
            - key: signing-certificate.pem
              path: signing-certificate.pem
            name: {{ template "nublado.fullname" . }}-jwt-cert
        - name: fs-mounts
          configMap:
            defaultMode: 420
            items:
            - key: mountpoints.json
              path: mountpoints.json
            name: {{ template "nublado.fullname" . }}-fs-mounts
        - name: resourcemap
          configMap:
            defaultMode: 420
            items:
            - key: resourcemap.json
              path: resourcemap.json
            name: {{ template "nublado.fullname" . }}-resourcemap
