kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.fullname" . }}-hub
rules:
rules:
- apiGroups: [""]
  resources: ["pods","events", "namespaces", "serviceaccounts", "services",
  "persistentvolumeclaims", "persistentvolumes", "resourcequotas",
  "configmaps"]
  verbs: ["get", "list", "create", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "create", "watch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows/finalizers"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtemplates"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtemplates/finalizers"]
  verbs: ["get", "list", "watch"]
