---
apiVersion: batch/v1
kind: Job
metadata:
  name: "saltransform-init"
  labels:
    helm.sh/chart: {{ include "kafka-efd-apps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        role: "saltransform-init"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: saltransformer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        command:
          - "kafkaefd"
          - "saltransform"
          - "init"
          - "--subsystem"
          - "MTM1M3TS"
          - "--subsystem"
          - "MTM1M3"
        env:
          - name: GITHUB_USER
            valueFrom:
              secretKeyRef:
                name: saltransformer-secrets
                key: GITHUB_USER
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: saltransformer-secrets
                key: GITHUB_TOKEN
          - name: BROKER
            value: "{{ .Values.env.broker }}"
          - name: SCHEMAREGISTRY
            value: "{{ .Values.env.schemaRegistry }}"
      restartPolicy: Never
  backoffLimit: 4
