# Default values for kafka-efd-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: lsstsqre/kafka-efd-demo
  tag: latest
  pullPolicy: Always

env:
  broker:  "confluent-cp-kafka-headless.kafka:9092"
  schemaRegistry: "http://confluent-cp-schema-registry.kafka:8081"
  kafkaConnect: "http://confluent-cp-kafka-connect:8083"
