apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly.fullname" . }}-secret
  labels:
{{ include "firefly.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- if .Values.admin_password }}
  "ADMIN_PASSWORD": "{{ .Values.admin_password }}"
{{- else }}
  "ADMIN_PASSWORD": "{{ randAlphaNum 32 }}"
{{- end }}
