apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect-manager.name" . }}
  labels:
    helm.sh/chart: {{ include "kafka-connect-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kafka-connect-manager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "kafka-connect-manager.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name:  {{ include "kafka-connect-manager.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        command:
        - connect_manager
        - create
        {{- if .Values.influxdb.enabled }}
        - influxdb-sink
        {{- end }}
        - --influxdb_url
        - {{ .Values.influxdb.influxdbUrl }}
        - --database
        - {{ .Values.influxdb.database }}
        - --tasks
        - "{{ .Values.influxdb.tasks }}"
        - --filter
        - {{ .Values.influxdb.filter }}
        - --error-policy
        - {{ .Values.influxdb.errorPolicy }}
        {{- if .Values.influxdb.autoUpdate }}
        - --auto-update
        - --check-interval
        - "{{ .Values.influxdb.checkInterval }}"
        {{- end }}
        {{- if .Values.influxdb.timestamp }}
        - --timestamp
        - "{{ .Values.influxdb.timestamp }}"
        {{- end }}
        env:
          - name: BROKER
            value: "{{ .Values.env.broker }}"
          - name: KAFKA_CONNECT
            value: "{{ .Values.env.kafkaConnect }}"
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxdb.existingSecret }}
                key: influxdb-user
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxdb.existingSecret }}
                key: influxdb-password
