apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cadc-tap.fullname" . }}-secret
  labels:
    app: {{ template "cadc-tap.fullname" . }}
{{ include "cadc-tap.labels" . | indent 4 }}
type: Opaque
data:
  "google_creds.json": {{ .Values.google_creds | b64enc }}
