kind: Service
apiVersion: v1
metadata:
  name: {{ template "cadc-tap.fullname" . }}
  labels:
    app: {{ template "cadc-tap.fullname" . }}
    chart: {{ template "cadc-tap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "cadc-tap.fullname" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
