apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap.fullname" . }}
  labels:
    app: {{ template "cadc-tap.fullname" . }}
    chart: {{ template "cadc-tap.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cadc-tap.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cadc-tap.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: google-creds
          mountPath: "/etc/creds"
          readOnly: true
        env:
        - name: CATALINA_OPTS
          # Presto backend
          value: "-Dqservuser.jdbc.username=qsmaster -Dqservuser.jdbc.password= -Dqservuser.jdbc.driverClassName=com.mysql.cj.jdbc.Driver -Dqservuser.jdbc.url=jdbc:mysql://{{template "cadc-tap.fullname" . }}-db:4040/ -Dtapuser.jdbc.username=TAP_SCHEMA -Dtapuser.jdbc.password=TAP_SCHEMA -Dtapuser.jdbc.driverClassName=com.mysql.cj.jdbc.Driver -Dtapuser.jdbc.url=jdbc:mysql://{{ template "cadc-tap.fullname" . }}-schema-db:3306/ -Dca.nrc.cadc.reg.client.RegistryClient.local=true -Duws.jdbc.username=postgres -Duws.jdbc.driverClassName=org.postgresql.Driver -Duws.jdbc.url=jdbc:postgresql://{{ template "cadc-tap.fullname" . }}-uws-db/ {{ .Values.extra_options }}"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/creds/google_creds.json"
      volumes:
      - name: google-creds
        secret:
          secretName: {{ template "cadc-tap.fullname" . }}-secret
